### ISSUE TITLE
Could not be built with spike 1.0.0

### ISSUE THREAD

**Issue by dyu** [static-dev/spike-www#37]
This also affects the other projects listed in https://spike.readme.io/docs/built-with-spike

After running yarn install, I get:
```sh
spike watch
/data/dyu/downloads/devtools/node/node-v6.9.0-linux-x64/lib/node_modules/spike/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
```

https://github.com/static-dev/spike-client-templates-example works though.

**Comment by jescalan** [comment]
Hi @dyu!

There was a major new release of spike recently that included a number of breaking changes. You can see the release notes as well as a migration guide here:

https://spike.readme.io/blog/v100

The reason the example works is because I updated all examples and plugins for compatibility with the latest version. In general, once you see the semver major version increase, it's a good idea to look out for breaking changes, since by definition, major releases include them. You can lock to the latest pre-1.0 release to keep compatibility with existing project, or you are welcome to follow to migration guide to update everything to the latest and greatest!
